# Generated by Django 4.0.6 on 2022-07-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emp_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
