# Generated by Django 4.0.6 on 2022-07-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0002_user_emp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='emp_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_name',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
