# Generated by Django 4.0.6 on 2022-07-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0003_alter_user_emp_id_alter_user_emp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendance_mail_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(default='', max_length=50)),
                ('emp_name', models.CharField(default='', max_length=50)),
                ('in_time', models.CharField(default='', max_length=50)),
                ('out_time', models.CharField(default='', max_length=50)),
                ('current_date', models.CharField(default='', max_length=50)),
                ('status', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_join',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='official_email_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_email_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default='', max_length=50),
        ),
    ]
