# Generated by Django 4.0.6 on 2022-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0004_attendance_mail_table_user_date_of_join_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance_mail_table',
            old_name='emp_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emp_name',
        ),
        migrations.AddField(
            model_name='user',
            name='adhar_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
