# Generated by Django 4.0.6 on 2022-07-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0009_clockin_emp_id_clockin_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clockin',
            name='current_time',
            field=models.DateTimeField(),
        ),
    ]
