# Generated by Django 4.0.6 on 2022-07-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0011_clockin_current_date_alter_clockin_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='clock_out_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
