# Generated by Django 4.0.6 on 2022-07-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0012_clockin_clock_out_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='clock_out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.CharField(default='', max_length=50)),
                ('clock_out_time', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('emp_id', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='clockin',
            name='clock_out_time',
        ),
    ]
