# Generated by Django 4.0.6 on 2022-07-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0015_rename_clock_out_time_clockout_clockout_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_clock_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_date', models.CharField(default='', max_length=50)),
                ('current_time', models.CharField(default='', max_length=50)),
                ('username', models.CharField(default='', max_length=50)),
                ('emp_id', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
