# Generated by Django 4.0.6 on 2022-07-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0016_user_clock_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_clock_in',
            name='button_color',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_clock_in',
            name='button_id',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_clock_in',
            name='button_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_clock_in',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user_clock_in',
            name='status',
            field=models.CharField(default='', max_length=50),
        ),
    ]
