# Generated by Django 4.0.6 on 2022-07-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0017_user_clock_in_button_color_user_clock_in_button_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_time_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('emp_id', models.CharField(default='', max_length=50)),
                ('user_clockin_time', models.CharField(default='', max_length=50)),
                ('user_clockout_time', models.CharField(default='', max_length=50)),
                ('user_current_date', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
