# Generated by Django 4.0.6 on 2022-07-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0018_user_time_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_time_log',
            name='user_total_hours',
            field=models.CharField(default='', max_length=50),
        ),
    ]
