# Generated by Django 4.0.6 on 2022-07-23 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0019_user_time_log_user_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
    ]
