# Generated by Django 4.0.6 on 2022-07-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0020_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='leave_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('emp_id', models.CharField(default='', max_length=50)),
                ('reason', models.CharField(default='', max_length=50)),
                ('leave_days', models.CharField(default='', max_length=50)),
                ('start_date', models.CharField(default='', max_length=50)),
                ('end_date', models.CharField(default='', max_length=50)),
                ('Billable_Status', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
