# Generated by Django 4.0.6 on 2022-07-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0022_leave_apply_discription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_apply',
            old_name='discription',
            new_name='description',
        ),
    ]
