# Generated by Django 4.0.6 on 2022-07-25 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0026_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_apply',
            name='current_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
