# Generated by Django 4.0.6 on 2022-07-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0029_alter_leave_apply_current_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='clockin',
            name='duration',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clockin',
            name='update_current_date',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='clockin',
            name='update_current_time',
            field=models.CharField(default='', max_length=50),
        ),
    ]
