# Generated by Django 4.0.6 on 2022-07-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0030_clockin_duration_clockin_update_current_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_clock_in',
            old_name='current_date',
            new_name='current_date_now',
        ),
        migrations.RenameField(
            model_name='user_clock_in',
            old_name='current_time',
            new_name='current_time_now',
        ),
    ]
