# Generated by Django 4.0.6 on 2022-07-29 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0031_rename_current_date_user_clock_in_current_date_now_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_clock_in',
            old_name='current_date_now',
            new_name='current_date',
        ),
        migrations.RenameField(
            model_name='user_clock_in',
            old_name='current_time_now',
            new_name='current_time',
        ),
    ]
