# Generated by Django 4.0.6 on 2022-08-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0034_leave_apply_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave_apply',
            name='rejeced_reason',
            field=models.CharField(default='', max_length=50),
        ),
    ]
