# Generated by Django 4.0.6 on 2022-08-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0035_leave_apply_rejeced_reason'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_apply',
            old_name='rejeced_reason',
            new_name='rejected_reason',
        ),
    ]
