# Generated by Django 4.0.6 on 2022-08-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0036_rename_rejeced_reason_leave_apply_rejected_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_time_log',
            name='attendance_form',
            field=models.CharField(default='', max_length=50),
        ),
    ]
