# Generated by Django 4.0.6 on 2022-08-05 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0037_user_time_log_attendance_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='acc_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='blood_group',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='ifsc_code',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='module',
            field=models.CharField(default='', max_length=50),
        ),
    ]
