# Generated by Django 4.0.6 on 2022-08-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0039_image_current_time_image_user_current_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='timesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(default='', max_length=150)),
                ('emp_id', models.CharField(default='', max_length=150)),
                ('project_name', models.CharField(default='', max_length=150)),
                ('project_code', models.CharField(default='', max_length=150)),
                ('job_name', models.CharField(default='', max_length=150)),
                ('status', models.CharField(default='', max_length=150)),
                ('work_status', models.CharField(default='', max_length=150)),
                ('posting_date', models.CharField(default='', max_length=150)),
                ('task_name', models.CharField(default='', max_length=150)),
                ('hours', models.CharField(default='', max_length=150)),
                ('date', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=500)),
                ('image', models.ImageField(null=True, upload_to='images_timesheet/')),
            ],
        ),
        migrations.CreateModel(
            name='timesheet_option_val',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=150)),
                ('project_code', models.CharField(default='', max_length=150)),
                ('job_name', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
