# Generated by Django 4.0.6 on 2022-08-17 09:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0041_location_remove_leave_apply_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='posting_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 17, 15, 5, 43, 52755)),
        ),
    ]
