# Generated by Django 4.0.6 on 2022-08-17 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0047_alter_timesheet_posting_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='date',
            new_name='today_date',
        ),
        migrations.AlterField(
            model_name='timesheet',
            name='posting_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
