# Generated by Django 4.0.6 on 2022-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0048_rename_date_timesheet_today_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='', max_length=150)),
                ('project_code', models.CharField(default='', max_length=150)),
                ('job_name', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
