# Generated by Django 4.0.6 on 2022-08-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0049_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_details_assign', models.CharField(default='', max_length=150)),
                ('username_assign', models.CharField(default='', max_length=150)),
            ],
        ),
    ]
