# Generated by Django 4.0.6 on 2022-08-19 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0050_assign_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assign_project',
            old_name='project_details_assign',
            new_name='job_name',
        ),
        migrations.AddField(
            model_name='assign_project',
            name='project_code',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='assign_project',
            name='project_name',
            field=models.CharField(default='', max_length=150),
        ),
    ]
