# Generated by Django 4.0.6 on 2022-08-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0051_rename_project_details_assign_assign_project_job_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.CharField(default='', max_length=50),
        ),
    ]
