# Generated by Django 4.0.6 on 2022-08-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0053_rename_user_timesheet_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='rejected_reason',
            field=models.ImageField(null=True, upload_to='images_timesheet/'),
        ),
    ]
