# Generated by Django 4.0.6 on 2022-08-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0056_rename_remarks_location_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(null=True, upload_to='user_images/'),
        ),
    ]
