# Generated by Django 4.0.6 on 2022-08-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0057_user_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.CharField(default='', max_length=500)),
                ('today_date', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
