# Generated by Django 4.0.6 on 2022-08-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0058_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='added_by',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='location',
            name='emp_id',
            field=models.CharField(default='', max_length=150),
        ),
    ]
