# Generated by Django 4.0.6 on 2022-08-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0059_location_added_by_location_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='username',
        ),
    ]
