# Generated by Django 4.0.6 on 2022-08-27 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0061_alter_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='hours',
            new_name='total_hours',
        ),
    ]
