# Generated by Django 4.0.6 on 2022-08-27 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0063_rename_total_hours_timesheet_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_mail_table',
            name='current_date',
        ),
    ]
