# Generated by Django 4.0.6 on 2022-08-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0065_rename_username_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
