# Generated by Django 4.0.6 on 2022-08-29 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0066_user_user_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='location',
            new_name='emp_location',
        ),
    ]
