# Generated by Django 4.0.6 on 2022-08-29 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0067_rename_location_emp_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timesheet',
            old_name='hours',
            new_name='total_hours',
        ),
    ]
