# Generated by Django 4.0.6 on 2022-08-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0069_rename_total_hours_timesheet_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesheet',
            name='rejected_reason',
            field=models.CharField(default='', max_length=500),
        ),
    ]
