# Generated by Django 4.0.6 on 2022-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0072_rename_note1_overall_work_hours_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lead',
            field=models.BooleanField(default=0),
        ),
    ]
