# Generated by Django 4.0.6 on 2022-09-06 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0073_user_is_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_name', models.CharField(default='', max_length=150)),
                ('module', models.CharField(default='', max_length=150)),
                ('username', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_lead',
        ),
    ]
