# Generated by Django 4.0.6 on 2022-09-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0074_assign_lead_remove_user_is_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_lead',
            field=models.BooleanField(default=0),
        ),
    ]
