# Generated by Django 4.0.6 on 2022-09-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0075_user_is_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='timesheet',
            name='leadname',
            field=models.CharField(default='', max_length=500),
        ),
    ]
