# Generated by Django 4.0.6 on 2022-09-07 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0077_assign_lead_lead_empid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave_apply',
            old_name='Billable_Status',
            new_name='lead_name',
        ),
    ]
