# Generated by Django 4.0.6 on 2022-09-20 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0080_user_time_log_calender_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_time_log',
            name='calender_form',
        ),
    ]
