# Generated by Django 4.0.6 on 2022-09-21 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0081_remove_user_time_log_calender_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_time_log',
            name='calender_form',
            field=models.CharField(default='', max_length=50),
        ),
    ]
