# Generated by Django 4.0.6 on 2022-09-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_tools', '0082_user_time_log_calender_form'),
    ]

    operations = [
        migrations.RenameField(
            model_name='overall_work_hours',
            old_name='date',
            new_name='dates',
        ),
    ]
